include $HOME/.config/i3/config-macropad.conf

bar {
    id primary
    output HDMI-0
    font pango:monospace 9
    status_command i3blocks
}

bar {
    id secondary
    output DP-1
    font pango:monospace 9
    status_command i3blocks -c $HOME/.config/i3blocks/second
    tray_output none
}

workspace 1 output HDMI-0
workspace 2 output HDMI-0
workspace 3 output HDMI-0
workspace 4 output HDMI-0
workspace 5 output HDMI-0
workspace 6 output DP-1
workspace 7 output DP-1
workspace 8 output DP-1
workspace 9 output DP-1
workspace 10 output DP-1
workspace 11 output DP-3
