bar {
    id primary
    output primary
    font pango:monospace 9
    status_command i3blocks -c $HOME/.config/i3blocks/config
}

bar {
    id secondary
    output nonprimary
    font pango:monospace 9
    status_command i3blocks -c $HOME/.config/i3blocks/second
    tray_output none
}

workspace 1 output primary
workspace 2 output primary
workspace 3 output primary
workspace 4 output primary
workspace 5 output primary
workspace 6 output nonprimary
workspace 7 output nonprimary
workspace 8 output nonprimary
workspace 9 output nonprimary
workspace 10 output nonprimary

exec_always --no-startup-id $HOME/.config/i3/recover-hdmi-after-resume --watch
