#!/bin/sh

volume=$(
    pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null |
        awk -F/ 'NR == 1 {gsub(/ /, "", $2); print $2}'
)
muted=$(
    pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null |
        awk '{print $2}'
)

if [ "$muted" = yes ]; then
    printf ' 🔊 muted \n'
elif [ -n "$volume" ]; then
    printf ' 🔊 %s \n' "$volume"
fi
